name: Compile and push the cls
on:
  push:
    branches:
      - master

jobs:
  compile-cls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
        sudo apt-get install texlive-latex-base
        latex *.ins
    - name: Commit files
      run: |
        git config --local user.email "danilo.pianini@gmail.com"
        git config --local user.name "Danilo Pianini [bot]"
        git add -f elsarticle.cls
        git commit -a -m "Update the cls file" || true
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
